services:
  dev:
    build:
      target: dev
      # context:,dockerfile: 省略
    restart: always
    volumes:
      - .:/app
      - /app/node_modules # node_modules を保護する
    ports:
      - "3000:3000"
    environment:
      PGHOST: db
      PGDATABASE: sample_db
      PGUSER: user
      PGPASSWORD: password
      PGPORT: 5432
      BASIC_AUTH_USER: admin
      BASIC_AUTH_PASS: supersecret5670
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: sample_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "3308:5432"

volumes:
  db-data:
