services:
  dev:
    build:
      target: dev
      # context:,dockerfile: 省略
    restart: always
    volumes:
      - .:/app
      - /app/node_modules # node_modules を保護する
    ports:
      - "3000:3000"
    environment:
      PGHOST: db
      PGDATABASE: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGPORT: 5432
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres:18
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      PGPASSWORD: ${PGPASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "3308:5432"

volumes:
  db-data:
