services:
  dev:
    build:
      target: dev
      # context:,dockerfile: 省略
    restart: always
    volumes:
      - .:/app
      - /app/node_modules # node_modules を保護する
    ports:
      - "3000:3000"
    environment:
      PGHOST: ${DB_HOST}
      PGDATABASE: ${DB_NAME}
      PGUSER: ${DB_USER}
      PGPASSWORD: ${DB_PASSWORD}
      PGPORT: 5432

      BASIC_AUTH_USER: admin
      BASIC_AUTH_PASS: supersecret5670

      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_NAME}

      REDIS_HOST: redis-db
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      postgres-db:
      redis-db
      
  postgres-db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "3308:5432"

  redis-db:
    image: redis:7.4-alpine
    container_name: redis
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  postgres-data:
  redis-data:
